### ISSUE TITLE
Update to #Factorio 0.13

### ISSUE THREAD

**Issue by jocker-il** [Suprcheese/Red-Alerts#2]
I've added hebrew to your mod :)

I hope you update it to version 0.13 - I couldn't test my addition just by changing the .json file - something about graphics...

 also - I'll be happy to make regular contributions to hebrew local in this mod as I do with other mods like FARL & EvoGUI

**Comment by Suprcheese** [comment]
Version 1.1.0 is updated for Factorio 0.13.
